=== surajnikam21/simplePatterns.py/venv/Lib/site-packages/of/schemas/namespaces/of/node/node.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Optimal Framework Node Schema",
  "title": "Node",
  "type": "object",
  "version": "0.1",
  "properties": {
    "_id": {
      "$ref": "ref://of.type#/properties/objectId",
      "description": "The objectId of the node.",
      "propertyId": "e9487ec8-dfce-440a-a5d5-e65e89bc84aa",
      "objectId": "true"
    },
    "parent_id": {
      "$ref": "ref://of.type#/properties/objectId",
      "description": "The parent objectId of the node. Empty if top node.",
      "refSchemaRef": "ref://of.node.node",
      "propertyId": "aaf26d75-480a-4176-b4c6-ee544a325ac2",
      "objectId": "true"
    },
    "name": {
      "description": "The friendly short name of the node.",
      "type": "string",
      "propertyId": "9ce4a360-53fe-4c02-b894-c5b1787cf835"
    },
    "description": {
      "description": "The descriptive text of the node.",
      "type": "string",
      "propertyId": "674286ab-55b8-4e3f-918f-8d3fd9593602"
    },
    "createdWhen": {
      "description": "The time the node was created",
      "type": "string",
      "format": "date-time",
      "propertyId": "293137d2-a97f-482d-8e29-2917b32f5e67"
    },
    "schemaRef": {
      "description": "The schema ref of the node schema, a URI.",
      "type": "string",
      "format": "uri",
      "propertyId": "e7b166f5-4bf0-4b8c-9a60-601030daa04b"
    },
    "canRead": {
      "description": "A list of the groups that can read the value of the node.",
      "type": "array",
      "items": {
        "$ref": "ref://of.type#/properties/objectId",
        "refSchemaRef": "ref://of.node.group",
        "propertyId": "5ede11e9-ccbe-425f-98ac-66d5136ed58b",
        "objectId": "true"
      },
      "minItems": 1
    },
    "canWrite": {
      "description": "A list of the groups that can write to the node(and create/delete subnodes).",
      "type": "array",
      "items": {
        "$ref": "ref://of.type#/properties/objectId",
        "refSchemaRef": "ref://of.node.group",
        "propertyId": "98286b6b-8cba-4086-8a71-2d754ac023b2",
        "objectId": "true"
      },
      "minItems": 1
    },
    "allowedChildTypes": {
      "description": "A list of the allowed types of children.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri",
        "propertyId": "9161503f-a3fe-4b7e-8c0a-8553bd3f8043"
      }
    },
    "templateName": {
      "description": "The name of the template used when creating the node",
      "type": "string",
      "propertyId": "5126fa0e-b258-4ac4-935a-c6d15a2e3681"
    }
  },
  "required": [
    "name",
    "createdWhen",
    "canRead",
    "canWrite",
    "schemaRef"
  ],
  "collection": "node",
  "namespace": "of"
}

=== surajnikam21/simplePatterns.py/venv/Lib/site-packages/of/broker/testing/init.json
[
  {
    "_id": "000000010000010001e64c00",
    "name": "Top",
    "description": "All system wide settings, users, permissions, rights ",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28"
    ],
    "canWrite": [
      "000000010000010001e64c28"
    ],
    "allowedChildTypes": [
      "ref://of.node.node"
    ]
  },
  {
    "_id": "000000010000010001e64c23",
    "parent_id": "000000010000010001e64c00",
    "name": "Administration",
    "description": "All system wide settings, users, permissions, rights ",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28"
    ],
    "canWrite": [
      "000000010000010001e64c28"
    ],
    "allowedChildTypes": [
      "ref://of.node.node"
    ]
  },
  {
    "_id": "000000010000010001e64c24",
    "parent_id": "000000010000010001e64c23",
    "name": "Groups",
    "description": "All groups and their settings",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28"
    ],
    "canWrite": [
      "000000010000010001e64c28"
    ],
    "allowedChildTypes": [
      "ref://of.node.group"
    ]
  },
  {
    "_id": "000000010000010001e64c25",
    "parent_id": "000000010000010001e64c23",
    "name": "Users",
    "description": "All users and their settings",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28"
    ],
    "canWrite": [
      "000000010000010001e64c28"
    ],
    "allowedChildTypes": [
      "ref://of.node.user"
    ]
  },
  {
    "_id": "000000010000010001e64c26",
    "parent_id": "000000010000010001e64c23",
    "name": "Rights",
    "description": "All the defined rights and their settings",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28"
    ],
    "canWrite": [
      "000000010000010001e64c28"
    ],
    "allowedChildTypes": [
      "ref://of.node.right"
    ]
  },
  {
    "_id": "000000010000010002e64d04",
    "parent_id": "000000010000010001e64c23",
    "name": "Templates",
    "description": "All templates",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28"
    ],
    "canWrite": [
      "000000010000010001e64c28"
    ],
    "allowedChildTypes": [
      "ref://of.node.node"
    ]
  },
  {
    "_id": "000000010000010002e64d03",
    "parent_id": "000000010000010001e64c00",
    "name": "Peers",
    "description": "The peers in the Optimal BPM system",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.node",
    "canRead": [
      "000000010000010001e64c28",
      "000000010000010001e64d02"
    ],
    "canWrite": [
      "000000010000010001e64c28",
      "000000010000010001e64d02"
    ],
    "allowedChildTypes": [
      "ref://of.node.broker",
      "ref://of.node.admin",
      "ref://of.node.peer",
      "bpm://node_agent"
    ]
  },
  {
    "_id": "000000010000010002e64d17",
    "parent_id": "000000010000010002e64d03",
    "name": "admin_root",
    "description": "The settings of the web admin interface for the user root",
    "createdWhen": "2014-11-13T01:00:00+00:00",
    "schemaRef": "ref://of.node.admin",
    "address": "admin_root",
    "canRead": [
      "000000010000010001e64c28",
      "000000010000010001e64d02"
    ],
    "canWrite": [
      "000000010000010001e64c28",
      "000000010000010001e64d02"
    ],
    "allowedChildTypes": []
  }
]
